Support multiple YubiKeys per user
neverpanic/simpleid-yubikey pull request #2
Opened 2017-01-02 20:26 UTC by J0s3f

Allow to use multiple yubikeys for the same user.
All IDs can be set in the config.
The changes are compatible with old configs, so no configuration changes are needed, except when adding more ids to a user.

2017-01-02 22:40 UTC, neverpanic requested changes
Some minor nitpicks, otherwise this looks good to go. Can you force-push over your branch with those fixes?

Thanks for working on this!

2017-01-02 22:40 UTC, neverpanic commented on extensions/yubikey/yubikey.extension.php
> +				if (isset($test_user['yubikey']['key_id']) && in_array($keyID, $test_user['yubikey']['key_id'], true)) {
You have a typo in the commit message of this commit. It should be `for each account`, but it `for ach account`.

2017-01-02 22:40 UTC, neverpanic commented on extensions/yubikey/yubikey.extension.php
> +	if(!is_array($yubi_user['key_id'])) {
I would prefer if you kept the same formatting rules used in the code already, i.e. a space after `if`.

2017-01-02 22:40 UTC, neverpanic commented on extensions/yubikey/yubikey.extension.php
> +				if(isset($test_user['yubikey']['key_id']) && !is_array($test_user['yubikey']['key_id'])) {
Space after `if` to match the existing formatting.

2017-02-13 11:16 UTC, J0s3f commented
I made the changes you suggested.

2017-02-13 12:35 UTC, merged

2017-02-13 12:40 UTC, neverpanic commented
Thanks, merged and released in 1.0.